"""
Models package for SkillFlow CRM
"""
from .user import User
from .sdc import SDC
from .work_order import WorkOrder, TrainingRoadmap, Invoice, Holiday, Alert
from .master_data import JobRoleMaster, MasterWorkOrder
from .resources import TrainerMaster, CenterManagerMaster, SDCInfrastructureMaster
from .schemas import (
    SessionRequest,
    SDCCreate,
    WorkOrderCreate,
    WorkOrderStartDate,
    RoadmapUpdate,
    InvoiceCreate,
    PaymentUpdate,
    HolidayCreate,
    UserRoleUpdate,
    JobRoleMasterCreate,
    JobRoleMasterUpdate,
    JobRoleAllocation,
    SDCDistrictAllocation,
    MasterWorkOrderCreate,
    MasterWorkOrderUpdate,
    SDCFromMasterCreate,
    TrainerCreate,
    TrainerUpdate,
    CenterManagerCreate,
    CenterManagerUpdate,
    SDCInfrastructureCreate,
    SDCInfrastructureUpdate,
    StageUpdateRequest,
    DeliverableUpdateRequest,
)

__all__ = [
    "User",
    "SDC",
    "WorkOrder",
    "TrainingRoadmap",
    "Invoice",
    "Holiday",
    "Alert",
    "JobRoleMaster",
    "MasterWorkOrder",
    "TrainerMaster",
    "CenterManagerMaster",
    "SDCInfrastructureMaster",
    "SessionRequest",
    "SDCCreate",
    "WorkOrderCreate",
    "WorkOrderStartDate",
    "RoadmapUpdate",
    "InvoiceCreate",
    "PaymentUpdate",
    "HolidayCreate",
    "UserRoleUpdate",
    "JobRoleMasterCreate",
    "JobRoleMasterUpdate",
    "JobRoleAllocation",
    "SDCDistrictAllocation",
    "MasterWorkOrderCreate",
    "MasterWorkOrderUpdate",
    "SDCFromMasterCreate",
    "TrainerCreate",
    "TrainerUpdate",
    "CenterManagerCreate",
    "CenterManagerUpdate",
    "SDCInfrastructureCreate",
    "SDCInfrastructureUpdate",
    "StageUpdateRequest",
    "DeliverableUpdateRequest",
]
